const { RmsIcon } = require("./enum")

exports.accountVerificationEmail = (name, email, link) => {
  return `<div style="display: flex; justify-content: center;"><div style="max-width: 700px;"> <header style="background-color:#1d3551; padding: 10px 50px;"> <img style="width: 120px;" src=${RmsIcon} alt="rml"> </header> <section style="background-color:#f4f3ef; padding: 10px 50px 50px 50px;"><h2>Account Verification</h2><p>Hi ${name},</p><p>You recently signed up on RMS Gloify with the email id ${email}. To verify this email belongs to you, please click on the button below:</p><div style="text-align: center; margin: 30px 0;"> <a href=${link} style="text-decoration: none; background-color: #fc6826;color: #f4f3ef;padding: 15px 50px;border: 0;border-radius:3px;font-size: 16px; cursor: pointer;"> Verify Email </a></div><p>If the link above does not work, copy and paste the following link in your browser.</p><p>${link}</p> </section></div></div>`
}

exports.resetPasswordEmail = (name, link) => {
  return `<div style="display: flex; justify-content: center;"><div style="max-width: 700px;"> <header style="background-color:#1d3551; padding: 10px 50px;"> <img style="width: 120px;" src=${RmsIcon} alt="rms"> </header> <section style="background-color:#f4f3ef; padding: 10px 50px 50px 50px;"><h2>Account Verification</h2><p>Hi ${name},</p><p>You requested help with your RMS Gloify Account for password reset. To reset your password please click on the button below:</p><div style="text-align: center; margin: 30px 0;"> <a href=${link} style="text-decoration: none; background-color: #fc6826;color: #f4f3ef;padding: 15px 50px;border: 0;border-radius:3px;font-size: 16px; cursor: pointer;"> Reset Password </a></div><p>For security reasons this link will not work after 1 hour.</p><p>If the link above does not work, copy and paste the following link in your browser.</p><p>${link}</p> </section></div></div>`
}

exports.invitationEmail = (name, sender, email, pass, link) => {
  return `<div style="display: flex; justify-content: center;"><div style="max-width: 700px;"> <header style="background-color:#1d3551; padding: 10px 50px;"> <img style="width: 120px;" src=${RmsIcon} alt="rms"> </header> <section style="background-color:#f4f3ef; padding: 10px 50px 50px 50px;"><h2>Invitation from RMS</h2><p>Hi ${name}, </p><p>${sender} has extended an invitation to you to join the Resource Management System. You can login using the email and password provided here, or you can reset your password by clicking on the icon below:</p><p>Email: ${email}</p><p>Password: ${pass}</p><div style="text-align: center; margin: 30px 0;"> <a href=${link} style="text-decoration: none; background-color: #fc6826;color: #f4f3ef;padding: 15px 50px;border: 0;border-radius:3px;font-size: 16px; cursor: pointer;"> Reset Password </a></div><p>For security reasons this link will not work after 24 hours.</p><p>If the link above does not work, copy and paste the following link in your browser.</p><p>${link}</p> </section></div></div>`
}